server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///mydb?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false